### PR TITLE
Workaround for #332 - iOS 13 Picture Notifications

### PR DESCRIPTION
**Pull request by NorthernMan54**
Workaround for iOS 13, and the requirement for motion sensors to be part of a camera in order for picture notifications.  Creates a dummy motion sensor and switch as part of the camera, and the switch turns the motion sensor on.  The motion sensor is automatically turned off after 5 seconds.

To enable picture notifications, create an Automation in the home app that turns on the dummy switch when the real motion sensor detects motion.

Also includes pull request #309

### CODE REVIEW

**Comment by KhaosT** [comment]
@NorthernMan54 can you add a config flag to conditionally setup the service for button and motion sensor?

**Comment by NorthernMan54** [comment]
Give me about 24 hours

**Comment by NorthernMan54** [comment]
@KhaosT We should be good to go

1 - Added "motion" as an option to create a dummy switch and motion sensor, defaults to false.
2 - Updated README for the config.json changes and a reference to the wiki for more detailed instructions
3 - Updated README for pull request #309 
4 - Also fixed #346, needed a couple more changes for the latest google API version.
5 - Moved google drive config instructions to the wiki

**Comment by ashtonaut** [comment]
Awesome, I'm looking forward to trying this out. Given that I'm liable to break my setup by messing with it before an official merge and update to homebridge-camera-ffmpeg, I might just wait for that and then get the new goodness via the official channel. Thanks heaps @NorthernMan54 - great solution!

**Comment by Maxwell70** [comment]
@KhaosT @NorthernMan54 Thank you for your work!!! When can I update the plugin to have a motion sensor and switch?

**Comment by KhaosT** [comment]
@NorthernMan54 Sweet! Thanks a lot!

**Pull request merged**
