### PR TITLE
New config keys 'minBitrate' and 'preserveRatio'

### PR DESCRIPTION
**Pull request by francesco-kriegel**
Hi

I added two new configuration keys that allow a more fine-grained control of the video output.  Please pull if appropriate.

Ciao
Francesco

### CODE REVIEW

**Comment by tgerring** [comment]
I'm interested in incorporating the ratio changes from this PR into master after #263 refactoring is merge

**Comment by francesco-kriegel** [comment]
Hi there

Would it please be possible that you reconsider this pull request?  I have merged my commit with your master branch, i.e., all conflicts have been resolved.  I can confirm that the merged code is functional.

Thanks in advance,
Francesco

**Comment by KhaosT** [comment]
Thanks for the contribution 🙏

**Comment by francesco-kriegel** [comment]
Thanks for merging 🙏

**Pull request merged**
